### ISSUE TITLE
How to change the extension name in `editor.defaultFormatter`.

### ISSUE THREAD

**Issue by EeyoreLee** [microsoft/vscode-python-tools-extension-template#152]
Hi, The extension namely yapf I published, but the name in `editor.defaultFormatter` is like `{publisher}.yapf`. How can I get a sample name instead of it.

**Comment by karthiknadig** [comment]
@EeyoreLee I am guessing it is this one: https://marketplace.visualstudio.com/items?itemName=22683d33-98ea-66f9-961d-cfe6a56b0234.yapf

You need to register a publisher name first. Then update the publishier id in the package.json. You probably want to delete the extension you have published.

Here are the steps:
1. Get a published id on the marketplace. For example, for the extensions we publish it is `ms-python`.
2. Update the publisher id in the package.json: https://github.com/microsoft/vscode-python-tools-extension-template/blob/11e5cbee621ff5b02d98b1c192c3951da69626c5/package.json#L11 to be the name you pick in step 1.
3. Then publish the extension with that publisher.

Since you have already published an extension you might want to delete that, otherwise the publishing tool will not let you publish it with the same extension id.

**Comment by EeyoreLee** [comment]
hi, thanks for replying @karthiknadig  - the one you guessed is right, and I already update the `package.json`. The problem is the `editor.defaultFormatter` param in vscode settings is below like
![image](https://github.com/microsoft/vscode-python-tools-extension-template/assets/49790022/5f0999d1-7b1e-456f-a006-ed6666d2b1a0)
I wanna have a name like the others, (ms-python.flake8) seems like `{name}.{extension name}` not `{publisher id}.{extension name}`

**Comment by EeyoreLee** [comment]
I know why it is. Is there any way I can modify my publisher? It seems that there is no way to modify once created :(

**Comment by EeyoreLee** [comment]
I create a sub-publisher, it works now. Thanks very much @karthiknadig
