### ISSUE TITLE
Any template extension fails to activate when no workspace is opened

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-python-tools-extension-template#66]
![image](https://user-images.githubusercontent.com/13199757/193949730-5ddfd09f-31c5-4076-b503-7e8d15ff569e.png)

https://github.com/microsoft/vscode-python-tools-extension-template/blob/620e863b5f6de9db092be3438c806154a7d5ae5a/src/common/settings.ts#L19-L29

can return an empty array if no workspaces are opened.

Consumers assume atleast one element exists in the array: https://github.com/microsoft/vscode-python-tools-extension-template/blob/620e863b5f6de9db092be3438c806154a7d5ae5a/src/extension.ts#L38

Causes issues like https://github.com/microsoft/vscode-black-formatter/issues/124.

**Comment by charliermarsh** [comment]
If it's helpful, I made a change in Ruff that seems to fix this (though I'll admit that I'm not really an expert on workspaces and the like -- I was mostly going off type signatures and my own testing): https://github.com/charliermarsh/ruff-vscode/pull/104

**Comment by karthiknadig** [comment]
I did not get the time to migrate the fix for this. `pylint`, `flake8` and `black` extensions have a generic fix for this. 

1. Ensure that TS selects and launches the server in the correct location.
2. Ensure that the `server.py` can work even if right information is not provided via TS. This is needed to allow users of the template to migrate the server to other IDEs where they can sue the executable directly like `neovim`
